=begin
#Pulp 3 API

#Fetch, Upload, Organize, and Distribute Software Packages

The version of the OpenAPI document: v3
Contact: pulp-list@redhat.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

# Common files
require 'pulp_deb_client/api_client'
require 'pulp_deb_client/api_error'
require 'pulp_deb_client/api_model_base'
require 'pulp_deb_client/version'
require 'pulp_deb_client/configuration'

# Models
require 'pulp_deb_client/models/apt_repository_sync_url'
require 'pulp_deb_client/models/async_operation_response'
require 'pulp_deb_client/models/content_summary_response'
require 'pulp_deb_client/models/copy'
require 'pulp_deb_client/models/deb_apt_distribution'
require 'pulp_deb_client/models/deb_apt_distribution_response'
require 'pulp_deb_client/models/deb_apt_publication'
require 'pulp_deb_client/models/deb_apt_publication_response'
require 'pulp_deb_client/models/deb_apt_remote'
require 'pulp_deb_client/models/deb_apt_remote_response'
require 'pulp_deb_client/models/deb_apt_remote_response_hidden_fields_inner'
require 'pulp_deb_client/models/deb_apt_repository'
require 'pulp_deb_client/models/deb_apt_repository_response'
require 'pulp_deb_client/models/deb_generic_content_response'
require 'pulp_deb_client/models/deb_installer_file_index'
require 'pulp_deb_client/models/deb_installer_file_index_response'
require 'pulp_deb_client/models/deb_installer_package_response'
require 'pulp_deb_client/models/deb_package_index'
require 'pulp_deb_client/models/deb_package_index_response'
require 'pulp_deb_client/models/deb_package_release_component'
require 'pulp_deb_client/models/deb_package_release_component_response'
require 'pulp_deb_client/models/deb_package_response'
require 'pulp_deb_client/models/deb_release'
require 'pulp_deb_client/models/deb_release_architecture'
require 'pulp_deb_client/models/deb_release_architecture_response'
require 'pulp_deb_client/models/deb_release_component'
require 'pulp_deb_client/models/deb_release_component_response'
require 'pulp_deb_client/models/deb_release_file'
require 'pulp_deb_client/models/deb_release_file_response'
require 'pulp_deb_client/models/deb_release_response'
require 'pulp_deb_client/models/deb_source_index'
require 'pulp_deb_client/models/deb_source_index_response'
require 'pulp_deb_client/models/deb_source_package'
require 'pulp_deb_client/models/deb_source_package_release_component'
require 'pulp_deb_client/models/deb_source_package_release_component_response'
require 'pulp_deb_client/models/deb_source_package_response'
require 'pulp_deb_client/models/deb_verbatim_publication'
require 'pulp_deb_client/models/deb_verbatim_publication_response'
require 'pulp_deb_client/models/my_permissions_response'
require 'pulp_deb_client/models/nested_role'
require 'pulp_deb_client/models/nested_role_response'
require 'pulp_deb_client/models/object_roles_response'
require 'pulp_deb_client/models/paginated_repository_version_response_list'
require 'pulp_deb_client/models/paginateddeb_apt_distribution_response_list'
require 'pulp_deb_client/models/paginateddeb_apt_publication_response_list'
require 'pulp_deb_client/models/paginateddeb_apt_remote_response_list'
require 'pulp_deb_client/models/paginateddeb_apt_repository_response_list'
require 'pulp_deb_client/models/paginateddeb_generic_content_response_list'
require 'pulp_deb_client/models/paginateddeb_installer_file_index_response_list'
require 'pulp_deb_client/models/paginateddeb_installer_package_response_list'
require 'pulp_deb_client/models/paginateddeb_package_index_response_list'
require 'pulp_deb_client/models/paginateddeb_package_release_component_response_list'
require 'pulp_deb_client/models/paginateddeb_package_response_list'
require 'pulp_deb_client/models/paginateddeb_release_architecture_response_list'
require 'pulp_deb_client/models/paginateddeb_release_component_response_list'
require 'pulp_deb_client/models/paginateddeb_release_file_response_list'
require 'pulp_deb_client/models/paginateddeb_release_response_list'
require 'pulp_deb_client/models/paginateddeb_source_index_response_list'
require 'pulp_deb_client/models/paginateddeb_source_package_release_component_response_list'
require 'pulp_deb_client/models/paginateddeb_source_package_response_list'
require 'pulp_deb_client/models/paginateddeb_verbatim_publication_response_list'
require 'pulp_deb_client/models/patcheddeb_apt_distribution'
require 'pulp_deb_client/models/patcheddeb_apt_remote'
require 'pulp_deb_client/models/patcheddeb_apt_repository'
require 'pulp_deb_client/models/policy_enum'
require 'pulp_deb_client/models/repair'
require 'pulp_deb_client/models/repository_add_remove_content'
require 'pulp_deb_client/models/repository_version_response'
require 'pulp_deb_client/models/set_label'
require 'pulp_deb_client/models/set_label_response'
require 'pulp_deb_client/models/unset_label'
require 'pulp_deb_client/models/unset_label_response'

# APIs
require 'pulp_deb_client/api/content_generic_contents_api'
require 'pulp_deb_client/api/content_installer_file_indices_api'
require 'pulp_deb_client/api/content_installer_packages_api'
require 'pulp_deb_client/api/content_package_indices_api'
require 'pulp_deb_client/api/content_package_release_components_api'
require 'pulp_deb_client/api/content_packages_api'
require 'pulp_deb_client/api/content_release_architectures_api'
require 'pulp_deb_client/api/content_release_components_api'
require 'pulp_deb_client/api/content_release_files_api'
require 'pulp_deb_client/api/content_releases_api'
require 'pulp_deb_client/api/content_source_indices_api'
require 'pulp_deb_client/api/content_source_packages_api'
require 'pulp_deb_client/api/content_source_release_components_api'
require 'pulp_deb_client/api/deb_copy_api'
require 'pulp_deb_client/api/distributions_apt_api'
require 'pulp_deb_client/api/publications_apt_api'
require 'pulp_deb_client/api/publications_verbatim_api'
require 'pulp_deb_client/api/remotes_apt_api'
require 'pulp_deb_client/api/repositories_apt_api'
require 'pulp_deb_client/api/repositories_apt_versions_api'

module PulpDebClient
  class << self
    # Customize default settings for the SDK using block.
    #   PulpDebClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
