=begin
#Pulp 3 API

#Fetch, Upload, Organize, and Distribute Software Packages

The version of the OpenAPI document: v3
Contact: pulp-list@redhat.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module PulpContainerClient
  # Serializer for Manifests.
  class ContainerManifestResponse < ApiModelBase
    attr_accessor :pulp_href

    # The Pulp Resource Name (PRN).
    attr_accessor :prn

    # Timestamp of creation.
    attr_accessor :pulp_created

    # Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
    attr_accessor :pulp_last_updated

    # A dictionary of arbitrary key/value pairs used to describe a specific Content instance.
    attr_accessor :pulp_labels

    attr_accessor :vuln_report

    # sha256 of the Manifest file
    attr_accessor :digest

    # Manifest schema version
    attr_accessor :schema_version

    # Manifest media type of the file
    attr_accessor :media_type

    # Manifests that are referenced by this Manifest List
    attr_accessor :listed_manifests

    # Blob that contains configuration for this Manifest
    attr_accessor :config_blob

    # Blobs that are referenced by this Manifest
    attr_accessor :blobs

    # Property that contains arbitrary metadata stored inside the image manifest.
    attr_accessor :annotations

    # Property describing metadata stored inside the image configuration
    attr_accessor :labels

    # A boolean determining whether users can boot from an image or not.[deprecated] check type field instead
    attr_accessor :is_bootable

    # A boolean determining whether the image bundles a Flatpak application.[deprecated] check type field instead
    attr_accessor :is_flatpak

    # Manifest type (flatpak, bootable, signature, etc.).
    attr_accessor :type

    # The CPU architecture which the binaries in this image are built to run on.
    attr_accessor :architecture

    # The name of the operating system which the image is built to run on.
    attr_accessor :os

    # Specifies the sum of the sizes, in bytes, of all compressed layers
    attr_accessor :compressed_image_size

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pulp_href' => :'pulp_href',
        :'prn' => :'prn',
        :'pulp_created' => :'pulp_created',
        :'pulp_last_updated' => :'pulp_last_updated',
        :'pulp_labels' => :'pulp_labels',
        :'vuln_report' => :'vuln_report',
        :'digest' => :'digest',
        :'schema_version' => :'schema_version',
        :'media_type' => :'media_type',
        :'listed_manifests' => :'listed_manifests',
        :'config_blob' => :'config_blob',
        :'blobs' => :'blobs',
        :'annotations' => :'annotations',
        :'labels' => :'labels',
        :'is_bootable' => :'is_bootable',
        :'is_flatpak' => :'is_flatpak',
        :'type' => :'type',
        :'architecture' => :'architecture',
        :'os' => :'os',
        :'compressed_image_size' => :'compressed_image_size'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pulp_href' => :'String',
        :'prn' => :'String',
        :'pulp_created' => :'Time',
        :'pulp_last_updated' => :'Time',
        :'pulp_labels' => :'Hash<String, String>',
        :'vuln_report' => :'String',
        :'digest' => :'String',
        :'schema_version' => :'Integer',
        :'media_type' => :'String',
        :'listed_manifests' => :'Array<String>',
        :'config_blob' => :'String',
        :'blobs' => :'Array<String>',
        :'annotations' => :'Object',
        :'labels' => :'Object',
        :'is_bootable' => :'Boolean',
        :'is_flatpak' => :'Boolean',
        :'type' => :'String',
        :'architecture' => :'String',
        :'os' => :'String',
        :'compressed_image_size' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PulpContainerClient::ContainerManifestResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PulpContainerClient::ContainerManifestResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pulp_href')
        self.pulp_href = attributes[:'pulp_href']
      end

      if attributes.key?(:'prn')
        self.prn = attributes[:'prn']
      end

      if attributes.key?(:'pulp_created')
        self.pulp_created = attributes[:'pulp_created']
      end

      if attributes.key?(:'pulp_last_updated')
        self.pulp_last_updated = attributes[:'pulp_last_updated']
      end

      if attributes.key?(:'pulp_labels')
        if (value = attributes[:'pulp_labels']).is_a?(Hash)
          self.pulp_labels = value
        end
      end

      if attributes.key?(:'vuln_report')
        self.vuln_report = attributes[:'vuln_report']
      end

      if attributes.key?(:'digest')
        self.digest = attributes[:'digest']
      else
        self.digest = nil
      end

      if attributes.key?(:'schema_version')
        self.schema_version = attributes[:'schema_version']
      else
        self.schema_version = nil
      end

      if attributes.key?(:'media_type')
        self.media_type = attributes[:'media_type']
      else
        self.media_type = nil
      end

      if attributes.key?(:'listed_manifests')
        if (value = attributes[:'listed_manifests']).is_a?(Array)
          self.listed_manifests = value
        end
      else
        self.listed_manifests = nil
      end

      if attributes.key?(:'config_blob')
        self.config_blob = attributes[:'config_blob']
      end

      if attributes.key?(:'blobs')
        if (value = attributes[:'blobs']).is_a?(Array)
          self.blobs = value
        end
      else
        self.blobs = nil
      end

      if attributes.key?(:'annotations')
        self.annotations = attributes[:'annotations']
      end

      if attributes.key?(:'labels')
        self.labels = attributes[:'labels']
      end

      if attributes.key?(:'is_bootable')
        self.is_bootable = attributes[:'is_bootable']
      else
        self.is_bootable = false
      end

      if attributes.key?(:'is_flatpak')
        self.is_flatpak = attributes[:'is_flatpak']
      else
        self.is_flatpak = false
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'architecture')
        self.architecture = attributes[:'architecture']
      end

      if attributes.key?(:'os')
        self.os = attributes[:'os']
      end

      if attributes.key?(:'compressed_image_size')
        self.compressed_image_size = attributes[:'compressed_image_size']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @digest.nil?
        invalid_properties.push('invalid value for "digest", digest cannot be nil.')
      end

      if @schema_version.nil?
        invalid_properties.push('invalid value for "schema_version", schema_version cannot be nil.')
      end

      if @media_type.nil?
        invalid_properties.push('invalid value for "media_type", media_type cannot be nil.')
      end

      if @listed_manifests.nil?
        invalid_properties.push('invalid value for "listed_manifests", listed_manifests cannot be nil.')
      end

      if @blobs.nil?
        invalid_properties.push('invalid value for "blobs", blobs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @digest.nil?
      return false if @schema_version.nil?
      return false if @media_type.nil?
      return false if @listed_manifests.nil?
      return false if @blobs.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] digest Value to be assigned
    def digest=(digest)
      if digest.nil?
        fail ArgumentError, 'digest cannot be nil'
      end

      @digest = digest
    end

    # Custom attribute writer method with validation
    # @param [Object] schema_version Value to be assigned
    def schema_version=(schema_version)
      if schema_version.nil?
        fail ArgumentError, 'schema_version cannot be nil'
      end

      @schema_version = schema_version
    end

    # Custom attribute writer method with validation
    # @param [Object] media_type Value to be assigned
    def media_type=(media_type)
      if media_type.nil?
        fail ArgumentError, 'media_type cannot be nil'
      end

      @media_type = media_type
    end

    # Custom attribute writer method with validation
    # @param [Object] listed_manifests Value to be assigned
    def listed_manifests=(listed_manifests)
      if listed_manifests.nil?
        fail ArgumentError, 'listed_manifests cannot be nil'
      end

      @listed_manifests = listed_manifests
    end

    # Custom attribute writer method with validation
    # @param [Object] blobs Value to be assigned
    def blobs=(blobs)
      if blobs.nil?
        fail ArgumentError, 'blobs cannot be nil'
      end

      @blobs = blobs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pulp_href == o.pulp_href &&
          prn == o.prn &&
          pulp_created == o.pulp_created &&
          pulp_last_updated == o.pulp_last_updated &&
          pulp_labels == o.pulp_labels &&
          vuln_report == o.vuln_report &&
          digest == o.digest &&
          schema_version == o.schema_version &&
          media_type == o.media_type &&
          listed_manifests == o.listed_manifests &&
          config_blob == o.config_blob &&
          blobs == o.blobs &&
          annotations == o.annotations &&
          labels == o.labels &&
          is_bootable == o.is_bootable &&
          is_flatpak == o.is_flatpak &&
          type == o.type &&
          architecture == o.architecture &&
          os == o.os &&
          compressed_image_size == o.compressed_image_size
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pulp_href, prn, pulp_created, pulp_last_updated, pulp_labels, vuln_report, digest, schema_version, media_type, listed_manifests, config_blob, blobs, annotations, labels, is_bootable, is_flatpak, type, architecture, os, compressed_image_size].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
