=begin
#Pulp 3 API

#Fetch, Upload, Organize, and Distribute Software Packages

The version of the OpenAPI document: v3
Contact: pulp-list@redhat.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'cgi'

module PulpAnsibleClient
  class ContentNamespacesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get the logo for the this namespace.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [nil]
    def avatar(ansible_ansible_namespace_metadata_href, opts = {})
      avatar_with_http_info(ansible_ansible_namespace_metadata_href, opts)
      nil
    end

    # Get the logo for the this namespace.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def avatar_with_http_info(ansible_ansible_namespace_metadata_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ContentNamespacesApi.avatar ...'
      end
      # verify the required parameter 'ansible_ansible_namespace_metadata_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_namespace_metadata_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_namespace_metadata_href' when calling ContentNamespacesApi.avatar"
      end
      # resource path
      local_var_path = '{ansible_ansible_namespace_metadata_href}avatar/'.sub('{' + 'ansible_ansible_namespace_metadata_href' + '}', CGI.escape(ansible_ansible_namespace_metadata_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"ContentNamespacesApi.avatar",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ContentNamespacesApi#avatar\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List ansible namespace metadatas
    # ViewSet for AnsibleNamespace.
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [String] :company Filter results where company matches value
    # @option opts [String] :company__contains Filter results where company contains value
    # @option opts [String] :company__icontains Filter results where company contains value
    # @option opts [String] :company__iexact Filter results where company matches value
    # @option opts [Array<String>] :company__in Filter results where company is in a comma-separated list of values
    # @option opts [String] :company__iregex Filter results where company matches regex value
    # @option opts [String] :company__istartswith Filter results where company starts with value
    # @option opts [String] :company__regex Filter results where company matches regex value
    # @option opts [String] :company__startswith Filter results where company starts with value
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [String] :metadata_sha256 Filter results where metadata_sha256 matches value
    # @option opts [Array<String>] :metadata_sha256__in Filter results where metadata_sha256 is in a comma-separated list of values
    # @option opts [String] :name Filter results where name matches value
    # @option opts [String] :name__contains Filter results where name contains value
    # @option opts [String] :name__icontains Filter results where name contains value
    # @option opts [String] :name__iexact Filter results where name matches value
    # @option opts [Array<String>] :name__in Filter results where name is in a comma-separated list of values
    # @option opts [String] :name__iregex Filter results where name matches regex value
    # @option opts [String] :name__istartswith Filter results where name starts with value
    # @option opts [String] :name__regex Filter results where name matches regex value
    # @option opts [String] :name__startswith Filter results where name starts with value
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [Array<String>] :ordering Ordering  * &#x60;pulp_id&#x60; - Pulp id * &#x60;-pulp_id&#x60; - Pulp id (descending) * &#x60;pulp_created&#x60; - Pulp created * &#x60;-pulp_created&#x60; - Pulp created (descending) * &#x60;pulp_last_updated&#x60; - Pulp last updated * &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending) * &#x60;pulp_type&#x60; - Pulp type * &#x60;-pulp_type&#x60; - Pulp type (descending) * &#x60;upstream_id&#x60; - Upstream id * &#x60;-upstream_id&#x60; - Upstream id (descending) * &#x60;pulp_labels&#x60; - Pulp labels * &#x60;-pulp_labels&#x60; - Pulp labels (descending) * &#x60;timestamp_of_interest&#x60; - Timestamp of interest * &#x60;-timestamp_of_interest&#x60; - Timestamp of interest (descending) * &#x60;name&#x60; - Name * &#x60;-name&#x60; - Name (descending) * &#x60;company&#x60; - Company * &#x60;-company&#x60; - Company (descending) * &#x60;email&#x60; - Email * &#x60;-email&#x60; - Email (descending) * &#x60;description&#x60; - Description * &#x60;-description&#x60; - Description (descending) * &#x60;resources&#x60; - Resources * &#x60;-resources&#x60; - Resources (descending) * &#x60;links&#x60; - Links * &#x60;-links&#x60; - Links (descending) * &#x60;avatar_sha256&#x60; - Avatar sha256 * &#x60;-avatar_sha256&#x60; - Avatar sha256 (descending) * &#x60;metadata_sha256&#x60; - Metadata sha256 * &#x60;-metadata_sha256&#x60; - Metadata sha256 (descending) * &#x60;pk&#x60; - Pk * &#x60;-pk&#x60; - Pk (descending)
    # @option opts [Float] :orphaned_for Minutes Content has been orphaned for. -1 uses ORPHAN_PROTECTION_TIME.
    # @option opts [Array<String>] :prn__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_href__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_id__in Multiple values may be separated by commas.
    # @option opts [String] :pulp_label_select Filter labels by search string
    # @option opts [String] :q Filter results by using NOT, AND and OR operations on other filters
    # @option opts [String] :repository_version Repository Version referenced by HREF/PRN
    # @option opts [String] :repository_version_added Repository Version referenced by HREF/PRN
    # @option opts [String] :repository_version_removed Repository Version referenced by HREF/PRN
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [PaginatedansibleAnsibleNamespaceMetadataResponseList]
    def list(opts = {})
      data, _status_code, _headers = list_with_http_info(opts)
      data
    end

    # List ansible namespace metadatas
    # ViewSet for AnsibleNamespace.
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [String] :company Filter results where company matches value
    # @option opts [String] :company__contains Filter results where company contains value
    # @option opts [String] :company__icontains Filter results where company contains value
    # @option opts [String] :company__iexact Filter results where company matches value
    # @option opts [Array<String>] :company__in Filter results where company is in a comma-separated list of values
    # @option opts [String] :company__iregex Filter results where company matches regex value
    # @option opts [String] :company__istartswith Filter results where company starts with value
    # @option opts [String] :company__regex Filter results where company matches regex value
    # @option opts [String] :company__startswith Filter results where company starts with value
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [String] :metadata_sha256 Filter results where metadata_sha256 matches value
    # @option opts [Array<String>] :metadata_sha256__in Filter results where metadata_sha256 is in a comma-separated list of values
    # @option opts [String] :name Filter results where name matches value
    # @option opts [String] :name__contains Filter results where name contains value
    # @option opts [String] :name__icontains Filter results where name contains value
    # @option opts [String] :name__iexact Filter results where name matches value
    # @option opts [Array<String>] :name__in Filter results where name is in a comma-separated list of values
    # @option opts [String] :name__iregex Filter results where name matches regex value
    # @option opts [String] :name__istartswith Filter results where name starts with value
    # @option opts [String] :name__regex Filter results where name matches regex value
    # @option opts [String] :name__startswith Filter results where name starts with value
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [Array<String>] :ordering Ordering  * &#x60;pulp_id&#x60; - Pulp id * &#x60;-pulp_id&#x60; - Pulp id (descending) * &#x60;pulp_created&#x60; - Pulp created * &#x60;-pulp_created&#x60; - Pulp created (descending) * &#x60;pulp_last_updated&#x60; - Pulp last updated * &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending) * &#x60;pulp_type&#x60; - Pulp type * &#x60;-pulp_type&#x60; - Pulp type (descending) * &#x60;upstream_id&#x60; - Upstream id * &#x60;-upstream_id&#x60; - Upstream id (descending) * &#x60;pulp_labels&#x60; - Pulp labels * &#x60;-pulp_labels&#x60; - Pulp labels (descending) * &#x60;timestamp_of_interest&#x60; - Timestamp of interest * &#x60;-timestamp_of_interest&#x60; - Timestamp of interest (descending) * &#x60;name&#x60; - Name * &#x60;-name&#x60; - Name (descending) * &#x60;company&#x60; - Company * &#x60;-company&#x60; - Company (descending) * &#x60;email&#x60; - Email * &#x60;-email&#x60; - Email (descending) * &#x60;description&#x60; - Description * &#x60;-description&#x60; - Description (descending) * &#x60;resources&#x60; - Resources * &#x60;-resources&#x60; - Resources (descending) * &#x60;links&#x60; - Links * &#x60;-links&#x60; - Links (descending) * &#x60;avatar_sha256&#x60; - Avatar sha256 * &#x60;-avatar_sha256&#x60; - Avatar sha256 (descending) * &#x60;metadata_sha256&#x60; - Metadata sha256 * &#x60;-metadata_sha256&#x60; - Metadata sha256 (descending) * &#x60;pk&#x60; - Pk * &#x60;-pk&#x60; - Pk (descending)
    # @option opts [Float] :orphaned_for Minutes Content has been orphaned for. -1 uses ORPHAN_PROTECTION_TIME.
    # @option opts [Array<String>] :prn__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_href__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_id__in Multiple values may be separated by commas.
    # @option opts [String] :pulp_label_select Filter labels by search string
    # @option opts [String] :q Filter results by using NOT, AND and OR operations on other filters
    # @option opts [String] :repository_version Repository Version referenced by HREF/PRN
    # @option opts [String] :repository_version_added Repository Version referenced by HREF/PRN
    # @option opts [String] :repository_version_removed Repository Version referenced by HREF/PRN
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(PaginatedansibleAnsibleNamespaceMetadataResponseList, Integer, Hash)>] PaginatedansibleAnsibleNamespaceMetadataResponseList data, response status code and response headers
    def list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ContentNamespacesApi.list ...'
      end
      allowable_values = ["-avatar_sha256", "-company", "-description", "-email", "-links", "-metadata_sha256", "-name", "-pk", "-pulp_created", "-pulp_id", "-pulp_labels", "-pulp_last_updated", "-pulp_type", "-resources", "-timestamp_of_interest", "-upstream_id", "avatar_sha256", "company", "description", "email", "links", "metadata_sha256", "name", "pk", "pulp_created", "pulp_id", "pulp_labels", "pulp_last_updated", "pulp_type", "resources", "timestamp_of_interest", "upstream_id"]
      if @api_client.config.client_side_validation && opts[:'ordering'] && !opts[:'ordering'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"ordering\", must include one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/pulp/api/v3/content/ansible/namespaces/'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'company'] = opts[:'company'] if !opts[:'company'].nil?
      query_params[:'company__contains'] = opts[:'company__contains'] if !opts[:'company__contains'].nil?
      query_params[:'company__icontains'] = opts[:'company__icontains'] if !opts[:'company__icontains'].nil?
      query_params[:'company__iexact'] = opts[:'company__iexact'] if !opts[:'company__iexact'].nil?
      query_params[:'company__in'] = @api_client.build_collection_param(opts[:'company__in'], :csv) if !opts[:'company__in'].nil?
      query_params[:'company__iregex'] = opts[:'company__iregex'] if !opts[:'company__iregex'].nil?
      query_params[:'company__istartswith'] = opts[:'company__istartswith'] if !opts[:'company__istartswith'].nil?
      query_params[:'company__regex'] = opts[:'company__regex'] if !opts[:'company__regex'].nil?
      query_params[:'company__startswith'] = opts[:'company__startswith'] if !opts[:'company__startswith'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'metadata_sha256'] = opts[:'metadata_sha256'] if !opts[:'metadata_sha256'].nil?
      query_params[:'metadata_sha256__in'] = @api_client.build_collection_param(opts[:'metadata_sha256__in'], :csv) if !opts[:'metadata_sha256__in'].nil?
      query_params[:'name'] = opts[:'name'] if !opts[:'name'].nil?
      query_params[:'name__contains'] = opts[:'name__contains'] if !opts[:'name__contains'].nil?
      query_params[:'name__icontains'] = opts[:'name__icontains'] if !opts[:'name__icontains'].nil?
      query_params[:'name__iexact'] = opts[:'name__iexact'] if !opts[:'name__iexact'].nil?
      query_params[:'name__in'] = @api_client.build_collection_param(opts[:'name__in'], :csv) if !opts[:'name__in'].nil?
      query_params[:'name__iregex'] = opts[:'name__iregex'] if !opts[:'name__iregex'].nil?
      query_params[:'name__istartswith'] = opts[:'name__istartswith'] if !opts[:'name__istartswith'].nil?
      query_params[:'name__regex'] = opts[:'name__regex'] if !opts[:'name__regex'].nil?
      query_params[:'name__startswith'] = opts[:'name__startswith'] if !opts[:'name__startswith'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?
      query_params[:'ordering'] = @api_client.build_collection_param(opts[:'ordering'], :csv) if !opts[:'ordering'].nil?
      query_params[:'orphaned_for'] = opts[:'orphaned_for'] if !opts[:'orphaned_for'].nil?
      query_params[:'prn__in'] = @api_client.build_collection_param(opts[:'prn__in'], :csv) if !opts[:'prn__in'].nil?
      query_params[:'pulp_href__in'] = @api_client.build_collection_param(opts[:'pulp_href__in'], :csv) if !opts[:'pulp_href__in'].nil?
      query_params[:'pulp_id__in'] = @api_client.build_collection_param(opts[:'pulp_id__in'], :csv) if !opts[:'pulp_id__in'].nil?
      query_params[:'pulp_label_select'] = opts[:'pulp_label_select'] if !opts[:'pulp_label_select'].nil?
      query_params[:'q'] = opts[:'q'] if !opts[:'q'].nil?
      query_params[:'repository_version'] = opts[:'repository_version'] if !opts[:'repository_version'].nil?
      query_params[:'repository_version_added'] = opts[:'repository_version_added'] if !opts[:'repository_version_added'].nil?
      query_params[:'repository_version_removed'] = opts[:'repository_version_removed'] if !opts[:'repository_version_removed'].nil?
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PaginatedansibleAnsibleNamespaceMetadataResponseList'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"ContentNamespacesApi.list",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ContentNamespacesApi#list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Inspect an ansible namespace metadata
    # ViewSet for AnsibleNamespace.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [AnsibleAnsibleNamespaceMetadataResponse]
    def read(ansible_ansible_namespace_metadata_href, opts = {})
      data, _status_code, _headers = read_with_http_info(ansible_ansible_namespace_metadata_href, opts)
      data
    end

    # Inspect an ansible namespace metadata
    # ViewSet for AnsibleNamespace.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(AnsibleAnsibleNamespaceMetadataResponse, Integer, Hash)>] AnsibleAnsibleNamespaceMetadataResponse data, response status code and response headers
    def read_with_http_info(ansible_ansible_namespace_metadata_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ContentNamespacesApi.read ...'
      end
      # verify the required parameter 'ansible_ansible_namespace_metadata_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_namespace_metadata_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_namespace_metadata_href' when calling ContentNamespacesApi.read"
      end
      # resource path
      local_var_path = '{ansible_ansible_namespace_metadata_href}'.sub('{' + 'ansible_ansible_namespace_metadata_href' + '}', CGI.escape(ansible_ansible_namespace_metadata_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AnsibleAnsibleNamespaceMetadataResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"ContentNamespacesApi.read",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ContentNamespacesApi#read\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Set a label
    # Set a single pulp_label on the object to a specific value or null.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param set_label [SetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [SetLabelResponse]
    def set_label(ansible_ansible_namespace_metadata_href, set_label, opts = {})
      data, _status_code, _headers = set_label_with_http_info(ansible_ansible_namespace_metadata_href, set_label, opts)
      data
    end

    # Set a label
    # Set a single pulp_label on the object to a specific value or null.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param set_label [SetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(SetLabelResponse, Integer, Hash)>] SetLabelResponse data, response status code and response headers
    def set_label_with_http_info(ansible_ansible_namespace_metadata_href, set_label, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ContentNamespacesApi.set_label ...'
      end
      # verify the required parameter 'ansible_ansible_namespace_metadata_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_namespace_metadata_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_namespace_metadata_href' when calling ContentNamespacesApi.set_label"
      end
      # verify the required parameter 'set_label' is set
      if @api_client.config.client_side_validation && set_label.nil?
        fail ArgumentError, "Missing the required parameter 'set_label' when calling ContentNamespacesApi.set_label"
      end
      # resource path
      local_var_path = '{ansible_ansible_namespace_metadata_href}set_label/'.sub('{' + 'ansible_ansible_namespace_metadata_href' + '}', CGI.escape(ansible_ansible_namespace_metadata_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(set_label)

      # return_type
      return_type = opts[:debug_return_type] || 'SetLabelResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"ContentNamespacesApi.set_label",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ContentNamespacesApi#set_label\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Unset a label
    # Unset a single pulp_label on the object.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param unset_label [UnsetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [UnsetLabelResponse]
    def unset_label(ansible_ansible_namespace_metadata_href, unset_label, opts = {})
      data, _status_code, _headers = unset_label_with_http_info(ansible_ansible_namespace_metadata_href, unset_label, opts)
      data
    end

    # Unset a label
    # Unset a single pulp_label on the object.
    # @param ansible_ansible_namespace_metadata_href [String] 
    # @param unset_label [UnsetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(UnsetLabelResponse, Integer, Hash)>] UnsetLabelResponse data, response status code and response headers
    def unset_label_with_http_info(ansible_ansible_namespace_metadata_href, unset_label, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ContentNamespacesApi.unset_label ...'
      end
      # verify the required parameter 'ansible_ansible_namespace_metadata_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_namespace_metadata_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_namespace_metadata_href' when calling ContentNamespacesApi.unset_label"
      end
      # verify the required parameter 'unset_label' is set
      if @api_client.config.client_side_validation && unset_label.nil?
        fail ArgumentError, "Missing the required parameter 'unset_label' when calling ContentNamespacesApi.unset_label"
      end
      # resource path
      local_var_path = '{ansible_ansible_namespace_metadata_href}unset_label/'.sub('{' + 'ansible_ansible_namespace_metadata_href' + '}', CGI.escape(ansible_ansible_namespace_metadata_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(unset_label)

      # return_type
      return_type = opts[:debug_return_type] || 'UnsetLabelResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"ContentNamespacesApi.unset_label",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ContentNamespacesApi#unset_label\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
