=begin
#Pulp 3 API

#Fetch, Upload, Organize, and Distribute Software Packages

The version of the OpenAPI document: v3
Contact: pulp-list@redhat.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'cgi'

module PulpAnsibleClient
  class RepositoriesAnsibleApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Add a role
    # Add a role for this object to users/groups.
    # @param ansible_ansible_repository_href [String] 
    # @param nested_role [NestedRole] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [NestedRoleResponse]
    def add_role(ansible_ansible_repository_href, nested_role, opts = {})
      data, _status_code, _headers = add_role_with_http_info(ansible_ansible_repository_href, nested_role, opts)
      data
    end

    # Add a role
    # Add a role for this object to users/groups.
    # @param ansible_ansible_repository_href [String] 
    # @param nested_role [NestedRole] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(NestedRoleResponse, Integer, Hash)>] NestedRoleResponse data, response status code and response headers
    def add_role_with_http_info(ansible_ansible_repository_href, nested_role, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.add_role ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.add_role"
      end
      # verify the required parameter 'nested_role' is set
      if @api_client.config.client_side_validation && nested_role.nil?
        fail ArgumentError, "Missing the required parameter 'nested_role' when calling RepositoriesAnsibleApi.add_role"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}add_role/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(nested_role)

      # return_type
      return_type = opts[:debug_return_type] || 'NestedRoleResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.add_role",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#add_role\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to copy collection versions.
    # @param ansible_ansible_repository_href [String] 
    # @param collection_version_copy_move [CollectionVersionCopyMove] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def copy_collection_version(ansible_ansible_repository_href, collection_version_copy_move, opts = {})
      data, _status_code, _headers = copy_collection_version_with_http_info(ansible_ansible_repository_href, collection_version_copy_move, opts)
      data
    end

    # Trigger an asynchronous task to copy collection versions.
    # @param ansible_ansible_repository_href [String] 
    # @param collection_version_copy_move [CollectionVersionCopyMove] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def copy_collection_version_with_http_info(ansible_ansible_repository_href, collection_version_copy_move, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.copy_collection_version ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.copy_collection_version"
      end
      # verify the required parameter 'collection_version_copy_move' is set
      if @api_client.config.client_side_validation && collection_version_copy_move.nil?
        fail ArgumentError, "Missing the required parameter 'collection_version_copy_move' when calling RepositoriesAnsibleApi.copy_collection_version"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}copy_collection_version/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(collection_version_copy_move)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.copy_collection_version",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#copy_collection_version\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create an ansible repository
    # ViewSet for Ansible Repositories.
    # @param ansible_ansible_repository [AnsibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AnsibleAnsibleRepositoryResponse]
    def create(ansible_ansible_repository, opts = {})
      data, _status_code, _headers = create_with_http_info(ansible_ansible_repository, opts)
      data
    end

    # Create an ansible repository
    # ViewSet for Ansible Repositories.
    # @param ansible_ansible_repository [AnsibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AnsibleAnsibleRepositoryResponse, Integer, Hash)>] AnsibleAnsibleRepositoryResponse data, response status code and response headers
    def create_with_http_info(ansible_ansible_repository, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.create ...'
      end
      # verify the required parameter 'ansible_ansible_repository' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository' when calling RepositoriesAnsibleApi.create"
      end
      # resource path
      local_var_path = '/pulp/api/v3/repositories/ansible/ansible/'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_ansible_repository)

      # return_type
      return_type = opts[:debug_return_type] || 'AnsibleAnsibleRepositoryResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.create",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete an ansible repository
    # Trigger an asynchronous delete task
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def delete(ansible_ansible_repository_href, opts = {})
      data, _status_code, _headers = delete_with_http_info(ansible_ansible_repository_href, opts)
      data
    end

    # Delete an ansible repository
    # Trigger an asynchronous delete task
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def delete_with_http_info(ansible_ansible_repository_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.delete ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.delete"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List ansible repositorys
    # ViewSet for Ansible Repositories.
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [String] :latest_with_content Content Unit referenced by HREF/PRN
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [String] :name Filter results where name matches value
    # @option opts [String] :name__contains Filter results where name contains value
    # @option opts [String] :name__icontains Filter results where name contains value
    # @option opts [String] :name__iexact Filter results where name matches value
    # @option opts [Array<String>] :name__in Filter results where name is in a comma-separated list of values
    # @option opts [String] :name__iregex Filter results where name matches regex value
    # @option opts [String] :name__istartswith Filter results where name starts with value
    # @option opts [String] :name__regex Filter results where name matches regex value
    # @option opts [String] :name__startswith Filter results where name starts with value
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [Array<String>] :ordering Ordering  * &#x60;pulp_id&#x60; - Pulp id * &#x60;-pulp_id&#x60; - Pulp id (descending) * &#x60;pulp_created&#x60; - Pulp created * &#x60;-pulp_created&#x60; - Pulp created (descending) * &#x60;pulp_last_updated&#x60; - Pulp last updated * &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending) * &#x60;pulp_type&#x60; - Pulp type * &#x60;-pulp_type&#x60; - Pulp type (descending) * &#x60;name&#x60; - Name * &#x60;-name&#x60; - Name (descending) * &#x60;pulp_labels&#x60; - Pulp labels * &#x60;-pulp_labels&#x60; - Pulp labels (descending) * &#x60;description&#x60; - Description * &#x60;-description&#x60; - Description (descending) * &#x60;next_version&#x60; - Next version * &#x60;-next_version&#x60; - Next version (descending) * &#x60;retain_repo_versions&#x60; - Retain repo versions * &#x60;-retain_repo_versions&#x60; - Retain repo versions (descending) * &#x60;user_hidden&#x60; - User hidden * &#x60;-user_hidden&#x60; - User hidden (descending) * &#x60;pk&#x60; - Pk * &#x60;-pk&#x60; - Pk (descending)
    # @option opts [Array<String>] :prn__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_href__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_id__in Multiple values may be separated by commas.
    # @option opts [String] :pulp_label_select Filter labels by search string
    # @option opts [String] :q Filter results by using NOT, AND and OR operations on other filters
    # @option opts [String] :remote Foreign Key referenced by HREF
    # @option opts [Integer] :retain_repo_versions Filter results where retain_repo_versions matches value
    # @option opts [Integer] :retain_repo_versions__gt Filter results where retain_repo_versions is greater than value
    # @option opts [Integer] :retain_repo_versions__gte Filter results where retain_repo_versions is greater than or equal to value
    # @option opts [Boolean] :retain_repo_versions__isnull Filter results where retain_repo_versions has a null value
    # @option opts [Integer] :retain_repo_versions__lt Filter results where retain_repo_versions is less than value
    # @option opts [Integer] :retain_repo_versions__lte Filter results where retain_repo_versions is less than or equal to value
    # @option opts [Integer] :retain_repo_versions__ne Filter results where retain_repo_versions not equal to value
    # @option opts [Array<Integer>] :retain_repo_versions__range Filter results where retain_repo_versions is between two comma separated values
    # @option opts [String] :with_content Content Unit referenced by HREF/PRN
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [PaginatedansibleAnsibleRepositoryResponseList]
    def list(opts = {})
      data, _status_code, _headers = list_with_http_info(opts)
      data
    end

    # List ansible repositorys
    # ViewSet for Ansible Repositories.
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [String] :latest_with_content Content Unit referenced by HREF/PRN
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [String] :name Filter results where name matches value
    # @option opts [String] :name__contains Filter results where name contains value
    # @option opts [String] :name__icontains Filter results where name contains value
    # @option opts [String] :name__iexact Filter results where name matches value
    # @option opts [Array<String>] :name__in Filter results where name is in a comma-separated list of values
    # @option opts [String] :name__iregex Filter results where name matches regex value
    # @option opts [String] :name__istartswith Filter results where name starts with value
    # @option opts [String] :name__regex Filter results where name matches regex value
    # @option opts [String] :name__startswith Filter results where name starts with value
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [Array<String>] :ordering Ordering  * &#x60;pulp_id&#x60; - Pulp id * &#x60;-pulp_id&#x60; - Pulp id (descending) * &#x60;pulp_created&#x60; - Pulp created * &#x60;-pulp_created&#x60; - Pulp created (descending) * &#x60;pulp_last_updated&#x60; - Pulp last updated * &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending) * &#x60;pulp_type&#x60; - Pulp type * &#x60;-pulp_type&#x60; - Pulp type (descending) * &#x60;name&#x60; - Name * &#x60;-name&#x60; - Name (descending) * &#x60;pulp_labels&#x60; - Pulp labels * &#x60;-pulp_labels&#x60; - Pulp labels (descending) * &#x60;description&#x60; - Description * &#x60;-description&#x60; - Description (descending) * &#x60;next_version&#x60; - Next version * &#x60;-next_version&#x60; - Next version (descending) * &#x60;retain_repo_versions&#x60; - Retain repo versions * &#x60;-retain_repo_versions&#x60; - Retain repo versions (descending) * &#x60;user_hidden&#x60; - User hidden * &#x60;-user_hidden&#x60; - User hidden (descending) * &#x60;pk&#x60; - Pk * &#x60;-pk&#x60; - Pk (descending)
    # @option opts [Array<String>] :prn__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_href__in Multiple values may be separated by commas.
    # @option opts [Array<String>] :pulp_id__in Multiple values may be separated by commas.
    # @option opts [String] :pulp_label_select Filter labels by search string
    # @option opts [String] :q Filter results by using NOT, AND and OR operations on other filters
    # @option opts [String] :remote Foreign Key referenced by HREF
    # @option opts [Integer] :retain_repo_versions Filter results where retain_repo_versions matches value
    # @option opts [Integer] :retain_repo_versions__gt Filter results where retain_repo_versions is greater than value
    # @option opts [Integer] :retain_repo_versions__gte Filter results where retain_repo_versions is greater than or equal to value
    # @option opts [Boolean] :retain_repo_versions__isnull Filter results where retain_repo_versions has a null value
    # @option opts [Integer] :retain_repo_versions__lt Filter results where retain_repo_versions is less than value
    # @option opts [Integer] :retain_repo_versions__lte Filter results where retain_repo_versions is less than or equal to value
    # @option opts [Integer] :retain_repo_versions__ne Filter results where retain_repo_versions not equal to value
    # @option opts [Array<Integer>] :retain_repo_versions__range Filter results where retain_repo_versions is between two comma separated values
    # @option opts [String] :with_content Content Unit referenced by HREF/PRN
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(PaginatedansibleAnsibleRepositoryResponseList, Integer, Hash)>] PaginatedansibleAnsibleRepositoryResponseList data, response status code and response headers
    def list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.list ...'
      end
      allowable_values = ["-description", "-name", "-next_version", "-pk", "-pulp_created", "-pulp_id", "-pulp_labels", "-pulp_last_updated", "-pulp_type", "-retain_repo_versions", "-user_hidden", "description", "name", "next_version", "pk", "pulp_created", "pulp_id", "pulp_labels", "pulp_last_updated", "pulp_type", "retain_repo_versions", "user_hidden"]
      if @api_client.config.client_side_validation && opts[:'ordering'] && !opts[:'ordering'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"ordering\", must include one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/pulp/api/v3/repositories/ansible/ansible/'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'latest_with_content'] = opts[:'latest_with_content'] if !opts[:'latest_with_content'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'name'] = opts[:'name'] if !opts[:'name'].nil?
      query_params[:'name__contains'] = opts[:'name__contains'] if !opts[:'name__contains'].nil?
      query_params[:'name__icontains'] = opts[:'name__icontains'] if !opts[:'name__icontains'].nil?
      query_params[:'name__iexact'] = opts[:'name__iexact'] if !opts[:'name__iexact'].nil?
      query_params[:'name__in'] = @api_client.build_collection_param(opts[:'name__in'], :csv) if !opts[:'name__in'].nil?
      query_params[:'name__iregex'] = opts[:'name__iregex'] if !opts[:'name__iregex'].nil?
      query_params[:'name__istartswith'] = opts[:'name__istartswith'] if !opts[:'name__istartswith'].nil?
      query_params[:'name__regex'] = opts[:'name__regex'] if !opts[:'name__regex'].nil?
      query_params[:'name__startswith'] = opts[:'name__startswith'] if !opts[:'name__startswith'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?
      query_params[:'ordering'] = @api_client.build_collection_param(opts[:'ordering'], :csv) if !opts[:'ordering'].nil?
      query_params[:'prn__in'] = @api_client.build_collection_param(opts[:'prn__in'], :csv) if !opts[:'prn__in'].nil?
      query_params[:'pulp_href__in'] = @api_client.build_collection_param(opts[:'pulp_href__in'], :csv) if !opts[:'pulp_href__in'].nil?
      query_params[:'pulp_id__in'] = @api_client.build_collection_param(opts[:'pulp_id__in'], :csv) if !opts[:'pulp_id__in'].nil?
      query_params[:'pulp_label_select'] = opts[:'pulp_label_select'] if !opts[:'pulp_label_select'].nil?
      query_params[:'q'] = opts[:'q'] if !opts[:'q'].nil?
      query_params[:'remote'] = opts[:'remote'] if !opts[:'remote'].nil?
      query_params[:'retain_repo_versions'] = opts[:'retain_repo_versions'] if !opts[:'retain_repo_versions'].nil?
      query_params[:'retain_repo_versions__gt'] = opts[:'retain_repo_versions__gt'] if !opts[:'retain_repo_versions__gt'].nil?
      query_params[:'retain_repo_versions__gte'] = opts[:'retain_repo_versions__gte'] if !opts[:'retain_repo_versions__gte'].nil?
      query_params[:'retain_repo_versions__isnull'] = opts[:'retain_repo_versions__isnull'] if !opts[:'retain_repo_versions__isnull'].nil?
      query_params[:'retain_repo_versions__lt'] = opts[:'retain_repo_versions__lt'] if !opts[:'retain_repo_versions__lt'].nil?
      query_params[:'retain_repo_versions__lte'] = opts[:'retain_repo_versions__lte'] if !opts[:'retain_repo_versions__lte'].nil?
      query_params[:'retain_repo_versions__ne'] = opts[:'retain_repo_versions__ne'] if !opts[:'retain_repo_versions__ne'].nil?
      query_params[:'retain_repo_versions__range'] = @api_client.build_collection_param(opts[:'retain_repo_versions__range'], :csv) if !opts[:'retain_repo_versions__range'].nil?
      query_params[:'with_content'] = opts[:'with_content'] if !opts[:'with_content'].nil?
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PaginatedansibleAnsibleRepositoryResponseList'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.list",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List roles
    # List roles assigned to this object.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [ObjectRolesResponse]
    def list_roles(ansible_ansible_repository_href, opts = {})
      data, _status_code, _headers = list_roles_with_http_info(ansible_ansible_repository_href, opts)
      data
    end

    # List roles
    # List roles assigned to this object.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(ObjectRolesResponse, Integer, Hash)>] ObjectRolesResponse data, response status code and response headers
    def list_roles_with_http_info(ansible_ansible_repository_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.list_roles ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.list_roles"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}list_roles/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ObjectRolesResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.list_roles",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#list_roles\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to mark Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_mark [AnsibleRepositoryMark] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def mark(ansible_ansible_repository_href, ansible_repository_mark, opts = {})
      data, _status_code, _headers = mark_with_http_info(ansible_ansible_repository_href, ansible_repository_mark, opts)
      data
    end

    # Trigger an asynchronous task to mark Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_mark [AnsibleRepositoryMark] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def mark_with_http_info(ansible_ansible_repository_href, ansible_repository_mark, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.mark ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.mark"
      end
      # verify the required parameter 'ansible_repository_mark' is set
      if @api_client.config.client_side_validation && ansible_repository_mark.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_repository_mark' when calling RepositoriesAnsibleApi.mark"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}mark/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_repository_mark)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.mark",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#mark\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Modify Repository Content
    # Trigger an asynchronous task to create a new repository version.
    # @param ansible_ansible_repository_href [String] 
    # @param repository_add_remove_content [RepositoryAddRemoveContent] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def modify(ansible_ansible_repository_href, repository_add_remove_content, opts = {})
      data, _status_code, _headers = modify_with_http_info(ansible_ansible_repository_href, repository_add_remove_content, opts)
      data
    end

    # Modify Repository Content
    # Trigger an asynchronous task to create a new repository version.
    # @param ansible_ansible_repository_href [String] 
    # @param repository_add_remove_content [RepositoryAddRemoveContent] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def modify_with_http_info(ansible_ansible_repository_href, repository_add_remove_content, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.modify ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.modify"
      end
      # verify the required parameter 'repository_add_remove_content' is set
      if @api_client.config.client_side_validation && repository_add_remove_content.nil?
        fail ArgumentError, "Missing the required parameter 'repository_add_remove_content' when calling RepositoriesAnsibleApi.modify"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}modify/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(repository_add_remove_content)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.modify",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#modify\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to move collection versions.
    # @param ansible_ansible_repository_href [String] 
    # @param collection_version_copy_move [CollectionVersionCopyMove] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def move_collection_version(ansible_ansible_repository_href, collection_version_copy_move, opts = {})
      data, _status_code, _headers = move_collection_version_with_http_info(ansible_ansible_repository_href, collection_version_copy_move, opts)
      data
    end

    # Trigger an asynchronous task to move collection versions.
    # @param ansible_ansible_repository_href [String] 
    # @param collection_version_copy_move [CollectionVersionCopyMove] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def move_collection_version_with_http_info(ansible_ansible_repository_href, collection_version_copy_move, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.move_collection_version ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.move_collection_version"
      end
      # verify the required parameter 'collection_version_copy_move' is set
      if @api_client.config.client_side_validation && collection_version_copy_move.nil?
        fail ArgumentError, "Missing the required parameter 'collection_version_copy_move' when calling RepositoriesAnsibleApi.move_collection_version"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}move_collection_version/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(collection_version_copy_move)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.move_collection_version",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#move_collection_version\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List user permissions
    # List permissions available to the current user on this object.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [MyPermissionsResponse]
    def my_permissions(ansible_ansible_repository_href, opts = {})
      data, _status_code, _headers = my_permissions_with_http_info(ansible_ansible_repository_href, opts)
      data
    end

    # List user permissions
    # List permissions available to the current user on this object.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(MyPermissionsResponse, Integer, Hash)>] MyPermissionsResponse data, response status code and response headers
    def my_permissions_with_http_info(ansible_ansible_repository_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.my_permissions ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.my_permissions"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}my_permissions/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MyPermissionsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.my_permissions",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#my_permissions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an ansible repository
    # Trigger an asynchronous partial update task
    # @param ansible_ansible_repository_href [String] 
    # @param patchedansible_ansible_repository [PatchedansibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def partial_update(ansible_ansible_repository_href, patchedansible_ansible_repository, opts = {})
      data, _status_code, _headers = partial_update_with_http_info(ansible_ansible_repository_href, patchedansible_ansible_repository, opts)
      data
    end

    # Update an ansible repository
    # Trigger an asynchronous partial update task
    # @param ansible_ansible_repository_href [String] 
    # @param patchedansible_ansible_repository [PatchedansibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def partial_update_with_http_info(ansible_ansible_repository_href, patchedansible_ansible_repository, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.partial_update ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.partial_update"
      end
      # verify the required parameter 'patchedansible_ansible_repository' is set
      if @api_client.config.client_side_validation && patchedansible_ansible_repository.nil?
        fail ArgumentError, "Missing the required parameter 'patchedansible_ansible_repository' when calling RepositoriesAnsibleApi.partial_update"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(patchedansible_ansible_repository)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.partial_update",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#partial_update\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Inspect an ansible repository
    # ViewSet for Ansible Repositories.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [AnsibleAnsibleRepositoryResponse]
    def read(ansible_ansible_repository_href, opts = {})
      data, _status_code, _headers = read_with_http_info(ansible_ansible_repository_href, opts)
      data
    end

    # Inspect an ansible repository
    # ViewSet for Ansible Repositories.
    # @param ansible_ansible_repository_href [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @option opts [Array<String>] :fields A list of fields to include in the response.
    # @option opts [Array<String>] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(AnsibleAnsibleRepositoryResponse, Integer, Hash)>] AnsibleAnsibleRepositoryResponse data, response status code and response headers
    def read_with_http_info(ansible_ansible_repository_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.read ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.read"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'fields'] = @api_client.build_collection_param(opts[:'fields'], :multi) if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = @api_client.build_collection_param(opts[:'exclude_fields'], :multi) if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AnsibleAnsibleRepositoryResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.read",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#read\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to rebuild Ansible content meta.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_rebuild [AnsibleRepositoryRebuild] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def rebuild_metadata(ansible_ansible_repository_href, ansible_repository_rebuild, opts = {})
      data, _status_code, _headers = rebuild_metadata_with_http_info(ansible_ansible_repository_href, ansible_repository_rebuild, opts)
      data
    end

    # Trigger an asynchronous task to rebuild Ansible content meta.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_rebuild [AnsibleRepositoryRebuild] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def rebuild_metadata_with_http_info(ansible_ansible_repository_href, ansible_repository_rebuild, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.rebuild_metadata ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.rebuild_metadata"
      end
      # verify the required parameter 'ansible_repository_rebuild' is set
      if @api_client.config.client_side_validation && ansible_repository_rebuild.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_repository_rebuild' when calling RepositoriesAnsibleApi.rebuild_metadata"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}rebuild_metadata/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_repository_rebuild)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.rebuild_metadata",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#rebuild_metadata\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Remove a role
    # Remove a role for this object from users/groups.
    # @param ansible_ansible_repository_href [String] 
    # @param nested_role [NestedRole] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [NestedRoleResponse]
    def remove_role(ansible_ansible_repository_href, nested_role, opts = {})
      data, _status_code, _headers = remove_role_with_http_info(ansible_ansible_repository_href, nested_role, opts)
      data
    end

    # Remove a role
    # Remove a role for this object from users/groups.
    # @param ansible_ansible_repository_href [String] 
    # @param nested_role [NestedRole] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(NestedRoleResponse, Integer, Hash)>] NestedRoleResponse data, response status code and response headers
    def remove_role_with_http_info(ansible_ansible_repository_href, nested_role, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.remove_role ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.remove_role"
      end
      # verify the required parameter 'nested_role' is set
      if @api_client.config.client_side_validation && nested_role.nil?
        fail ArgumentError, "Missing the required parameter 'nested_role' when calling RepositoriesAnsibleApi.remove_role"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}remove_role/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(nested_role)

      # return_type
      return_type = opts[:debug_return_type] || 'NestedRoleResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.remove_role",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#remove_role\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Set a label
    # Set a single pulp_label on the object to a specific value or null.
    # @param ansible_ansible_repository_href [String] 
    # @param set_label [SetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [SetLabelResponse]
    def set_label(ansible_ansible_repository_href, set_label, opts = {})
      data, _status_code, _headers = set_label_with_http_info(ansible_ansible_repository_href, set_label, opts)
      data
    end

    # Set a label
    # Set a single pulp_label on the object to a specific value or null.
    # @param ansible_ansible_repository_href [String] 
    # @param set_label [SetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(SetLabelResponse, Integer, Hash)>] SetLabelResponse data, response status code and response headers
    def set_label_with_http_info(ansible_ansible_repository_href, set_label, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.set_label ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.set_label"
      end
      # verify the required parameter 'set_label' is set
      if @api_client.config.client_side_validation && set_label.nil?
        fail ArgumentError, "Missing the required parameter 'set_label' when calling RepositoriesAnsibleApi.set_label"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}set_label/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(set_label)

      # return_type
      return_type = opts[:debug_return_type] || 'SetLabelResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.set_label",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#set_label\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to sign Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_signature [AnsibleRepositorySignature] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def sign(ansible_ansible_repository_href, ansible_repository_signature, opts = {})
      data, _status_code, _headers = sign_with_http_info(ansible_ansible_repository_href, ansible_repository_signature, opts)
      data
    end

    # Trigger an asynchronous task to sign Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_signature [AnsibleRepositorySignature] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def sign_with_http_info(ansible_ansible_repository_href, ansible_repository_signature, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.sign ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.sign"
      end
      # verify the required parameter 'ansible_repository_signature' is set
      if @api_client.config.client_side_validation && ansible_repository_signature.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_repository_signature' when calling RepositoriesAnsibleApi.sign"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}sign/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_repository_signature)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.sign",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#sign\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to sync Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_sync_url [AnsibleRepositorySyncURL] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def sync(ansible_ansible_repository_href, ansible_repository_sync_url, opts = {})
      data, _status_code, _headers = sync_with_http_info(ansible_ansible_repository_href, ansible_repository_sync_url, opts)
      data
    end

    # Trigger an asynchronous task to sync Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_sync_url [AnsibleRepositorySyncURL] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def sync_with_http_info(ansible_ansible_repository_href, ansible_repository_sync_url, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.sync ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.sync"
      end
      # verify the required parameter 'ansible_repository_sync_url' is set
      if @api_client.config.client_side_validation && ansible_repository_sync_url.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_repository_sync_url' when calling RepositoriesAnsibleApi.sync"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}sync/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_repository_sync_url)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.sync",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#sync\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Trigger an asynchronous task to unmark Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_mark [AnsibleRepositoryMark] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def unmark(ansible_ansible_repository_href, ansible_repository_mark, opts = {})
      data, _status_code, _headers = unmark_with_http_info(ansible_ansible_repository_href, ansible_repository_mark, opts)
      data
    end

    # Trigger an asynchronous task to unmark Ansible content.
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_repository_mark [AnsibleRepositoryMark] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def unmark_with_http_info(ansible_ansible_repository_href, ansible_repository_mark, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.unmark ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.unmark"
      end
      # verify the required parameter 'ansible_repository_mark' is set
      if @api_client.config.client_side_validation && ansible_repository_mark.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_repository_mark' when calling RepositoriesAnsibleApi.unmark"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}unmark/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_repository_mark)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.unmark",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#unmark\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Unset a label
    # Unset a single pulp_label on the object.
    # @param ansible_ansible_repository_href [String] 
    # @param unset_label [UnsetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [UnsetLabelResponse]
    def unset_label(ansible_ansible_repository_href, unset_label, opts = {})
      data, _status_code, _headers = unset_label_with_http_info(ansible_ansible_repository_href, unset_label, opts)
      data
    end

    # Unset a label
    # Unset a single pulp_label on the object.
    # @param ansible_ansible_repository_href [String] 
    # @param unset_label [UnsetLabel] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(UnsetLabelResponse, Integer, Hash)>] UnsetLabelResponse data, response status code and response headers
    def unset_label_with_http_info(ansible_ansible_repository_href, unset_label, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.unset_label ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.unset_label"
      end
      # verify the required parameter 'unset_label' is set
      if @api_client.config.client_side_validation && unset_label.nil?
        fail ArgumentError, "Missing the required parameter 'unset_label' when calling RepositoriesAnsibleApi.unset_label"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}unset_label/'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(unset_label)

      # return_type
      return_type = opts[:debug_return_type] || 'UnsetLabelResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.unset_label",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#unset_label\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an ansible repository
    # Trigger an asynchronous update task
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_ansible_repository [AnsibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [AsyncOperationResponse]
    def update(ansible_ansible_repository_href, ansible_ansible_repository, opts = {})
      data, _status_code, _headers = update_with_http_info(ansible_ansible_repository_href, ansible_ansible_repository, opts)
      data
    end

    # Update an ansible repository
    # Trigger an asynchronous update task
    # @param ansible_ansible_repository_href [String] 
    # @param ansible_ansible_repository [AnsibleAnsibleRepository] 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<String>] :x_task_diagnostics List of profilers to use on tasks.
    # @return [Array<(AsyncOperationResponse, Integer, Hash)>] AsyncOperationResponse data, response status code and response headers
    def update_with_http_info(ansible_ansible_repository_href, ansible_ansible_repository, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesAnsibleApi.update ...'
      end
      # verify the required parameter 'ansible_ansible_repository_href' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository_href' when calling RepositoriesAnsibleApi.update"
      end
      # verify the required parameter 'ansible_ansible_repository' is set
      if @api_client.config.client_side_validation && ansible_ansible_repository.nil?
        fail ArgumentError, "Missing the required parameter 'ansible_ansible_repository' when calling RepositoriesAnsibleApi.update"
      end
      # resource path
      local_var_path = '{ansible_ansible_repository_href}'.sub('{' + 'ansible_ansible_repository_href' + '}', CGI.escape(ansible_ansible_repository_href.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Task-Diagnostics'] = @api_client.build_collection_param(opts[:'x_task_diagnostics'], :csv) if !opts[:'x_task_diagnostics'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ansible_ansible_repository)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncOperationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['remoteUserAuthentication']

      new_options = opts.merge(
        :operation => :"RepositoriesAnsibleApi.update",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesAnsibleApi#update\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
